export const baseEmployee = [
  {
    id: 1,
    firstName: "Vengadesan",
    lastName: "Ramachandran",
    email: "vengadesan.r@company.in",
    department: "Engineering",
    role: "Senior Developer",
  },
  {
    id: 2,
    firstName: "Iyappan",
    lastName: "Vijay",
    email: "iyappan.v@company.in",
    department: "HR",
    role: "HR Manager",
  },
  {
    id: 3,
    firstName: "Suriya",
    lastName: "Sethupathi",
    email: "suriya.s@company.in",
    department: "Marketing",
    role: "Marketing Specialist",
  },
  {
    id: 4,
    firstName: "Kamal",
    lastName: "Rajini",
    email: "kamal.r@company.in",
    department: "Engineering",
    role: "Frontend Developer",
  },
  {
    id: 5,
    firstName: "Robert",
    lastName: "Downey",
    email: "robert.d@company.in",
    department: "Sales",
    role: "Sales Representative",
  },
  {
    id: 6,
    firstName: "Will",
    lastName: "Smith",
    email: "will.smith@company.in",
    department: "Finance",
    role: "Financial Analyst",
  },
  {
    id: 7,
    firstName: "Jackie",
    lastName: "Chan",
    email: "jackie.chan@company.in",
    department: "Engineering",
    role: "DevOps Engineer",
  },
  {
    id: 8,
    firstName: "Raj",
    lastName: "Kumar",
    email: "raj.kumar@company.in",
    department: "HR",
    role: "Recruiter",
  },
  {
    id: 9,
    firstName: "Nagendran",
    lastName: "Prakash",
    email: "nagendran.p@company.in",
    department: "Engineering",
    role: "Backend Developer",
  },
  {
    id: 10,
    firstName: "Ganesh",
    lastName: "Ashok",
    email: "ganesh.a@company.in",
    department: "Finance",
    role: "Accounts Manager",
  },
  {
    id: 11,
    firstName: "Palaniyandi",
    lastName: "Ramkuram",
    email: "palaniyandi.r@company.in",
    department: "Sales",
    role: "Territory Manager",
  },
  {
    id: 12,
    firstName: "Karthik",
    lastName: "Raja",
    email: "karthik.raja@company.in",
    department: "Engineering",
    role: "Software Engineer",
  },
  {
    id: 13,
    firstName: "Arun",
    lastName: "Mohan",
    email: "arun.mohan@company.in",
    department: "HR",
    role: "HR Executive",
  },
  {
    id: 14,
    firstName: "Meena",
    lastName: "Devi",
    email: "meena.devi@company.in",
    department: "Marketing",
    role: "Content Writer",
  },
  {
    id: 15,
    firstName: "Vishal",
    lastName: "Krishna",
    email: "vishal.k@company.in",
    department: "Engineering",
    role: "Full Stack Developer",
  },
  {
    id: 16,
    firstName: "Priya",
    lastName: "Sundar",
    email: "priya.s@company.in",
    department: "Sales",
    role: "Sales Executive",
  },
  {
    id: 17,
    firstName: "Divya",
    lastName: "Bharathi",
    email: "divya.b@company.in",
    department: "Finance",
    role: "Tax Consultant",
  },
  {
    id: 18,
    firstName: "Ravi",
    lastName: "Teja",
    email: "ravi.t@company.in",
    department: "Engineering",
    role: "Cloud Engineer",
  },
  {
    id: 19,
    firstName: "Deepika",
    lastName: "Kumari",
    email: "deepika.k@company.in",
    department: "HR",
    role: "HR Intern",
  },
  {
    id: 20,
    firstName: "Manoj",
    lastName: "Joshi",
    email: "manoj.j@company.in",
    department: "Marketing",
    role: "SEO Analyst",
  },
  {
    id: 21,
    firstName: "Sneha",
    lastName: "Kapoor",
    email: "sneha.k@company.in",
    department: "Engineering",
    role: "UI/UX Designer",
  },
  {
    id: 22,
    firstName: "Anil",
    lastName: "Sharma",
    email: "anil.s@company.in",
    department: "Sales",
    role: "Area Manager",
  },
  {
    id: 23,
    firstName: "Lakshmi",
    lastName: "Nair",
    email: "lakshmi.n@company.in",
    department: "Finance",
    role: "Auditor",
  },
  {
    id: 24,
    firstName: "Ajay",
    lastName: "Singh",
    email: "ajay.singh@company.in",
    department: "Engineering",
    role: "System Architect",
  },
  {
    id: 25,
    firstName: "Neha",
    lastName: "Patel",
    email: "neha.p@company.in",
    department: "HR",
    role: "Talent Specialist",
  },
  {
    id: 26,
    firstName: "Rahul",
    lastName: "Verma",
    email: "rahul.v@company.in",
    department: "Marketing",
    role: "Brand Strategist",
  },
  {
    id: 27,
    firstName: "Sathish",
    lastName: "Kumar",
    email: "sathish.k@company.in",
    department: "Engineering",
    role: "Mobile Developer",
  },
  {
    id: 28,
    firstName: "Pooja",
    lastName: "Reddy",
    email: "pooja.r@company.in",
    department: "Sales",
    role: "Sales Analyst",
  },
  {
    id: 29,
    firstName: "Abhishek",
    lastName: "Tiwari",
    email: "abhishek.t@company.in",
    department: "Finance",
    role: "Investment Analyst",
  },
  {
    id: 30,
    firstName: "Revathi",
    lastName: "Menon",
    email: "revathi.m@company.in",
    department: "Engineering",
    role: "Security Engineer",
  },
];
